[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
        default-src 'self';
        base-uri 'none';
        upgrade-insecure-requests;
    """
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "https://nooverviewavailable.netlify.com/*"
  to = "https://nooverviewavailable.com/:splat"

[[redirects]]
  from = "http://nooverviewavailable.netlify.com/*"
  to = "https://nooverviewavailable.com/:splat"
